### ISSUE TITLE
Document `-Q` option

### ISSUE THREAD

**Issue by nsoranzo** [agordon/fastx_toolkit#19]
All tools parse (and many use) the [`-Q` option](https://github.com/agordon/fastx_toolkit/blob/master/src/libfastx/fastx_args.c#L128) to specify the quality offset, with default 33. However this is not documented on the website or when using the `-h` option of the interested tools.

**Comment by agordon** [comment]
Hello @nsoranzo ,

You are correct, "-Q" is not well documented.
On the other hand, "fastx toolkit" has been unmaintained since 2010 - There are modern (and better) tools out there and I don't recommend new users to use it.

However, if you want to send a patch to add "-Q", please do so.

regards,
gordon

**Comment by keenhl** [comment]
What tools would you recommend?  Thanks for the advice.
