### ISSUE TITLE
No "configure" file

### ISSUE THREAD

**Issue by bosborne** [agordon/fastx_toolkit#8]
There is no "configure" in https://github.com/agordon/fastx_toolkit/archive/0.0.14.tar.gz, just "configure.ac".

    Installation
    ============
    
    To compile to tools, run:
    
      $ ./configure
      $ make
  
I ran "autoreconf -fvi" to make it and the Makefile, but the README is incorrect.

**Comment by agordon** [comment]
Hello @bosborne,

Thanks for writing. However, the README is not 'incorrect', and this issue is not a problem in 'fasts-toolkit'. The github automatic release archives for git-tags is COMPLETELY broken for autotools-based projects (those that use `make dist`), and therefor should not be used. I wish there was a way to disable them or hide them.

For an autotools-based project, downloading this 'automatically generated' archive (the tar.gz/zip files) is exactly the same as doing a `git clone`, and thus of course it requires running `autoreconf` (or alternatively  running the `reconf` script that's included in fastx-toolkit).

The officially released tarball is listed slightly below, under **downloads**, in this URL: https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2 .
That is the correct file to download if you wish to just run `configure` .

See more details here: https://github.com/vcftools/vcftools/issues/20#issuecomment-147155809 .

regards,
assaf
